GDevelopApp/GDevelop-examples

.gitignore

I have tested it by opening some projects and opening a preview, and github desktop seems to ignore the created autosaves now works fine for me
:)

Added .autosave to .gitignore

---

examples/not-a-vania/not-a-vania.json

- Fix debug events not working in web-app

Update not-a-vania by Silver-Streak

---

examples/breakout/breakout.json

Close https://github.com/GDevelopApp/GDevelop-examples/issues/65

Fix resources from Breakout example

---

examples/random-number-or-string-from-a-list/random-number-or-string-from-a-list.json
examples/rhythm/rhythm.json
examples/shootalia-top-down-shooter/shootalia-top-down-shooter.json
examples/tic-tac-toe/tic-tac-toe.json
examples/yarnalia/yarnalia.json

Updated examples by Ulises Freitas and Jurfix
✅️ - Author name updated
⛔️ - Username not found
not-a-vania: Silver-Streak ✅️
cannon-ball-with-physics: The Gem Dev ✅️
menu-with-functions-and-text-effects: Phenomena ⛔️
geometry-monster: mypoint13k ⛔️
z-depth: gametemplates.itch.io ✅️
particle-effects-demo: Wishforge Games ⛔️
breakout: Midhil M(Leo Red) ✅️
reflective-surface: VegeTato ✅️
procedural-generation: Add00 ✅️
shootalia-top-down-shooter: Ulises Freitas <ulises.freitas@gmail.com> ✅️
level-selection-unlock: ddabrahim gametemplates.itch.io ✅️
marching-squares-liquids: D8H ✅️
marching-squares-fog-of-war: D8H ✅️
magnet: Entropy ✅️
video-player: Bouh ✅️
screen-shake: Zat ⛔️
snap-object-to-grid: @Lizard-13 ⛔️ , D8H ✅️
tic-tac-toe: Jurfix (Yaroslav Nazarenko) ✅️
lights: Midhil M (Leo Red) …

Properties update 2

---

examples/virtual-joystick/README.md

Add a short note on how virtual joysticks can be useful
Adds credit to kenney assets for the art (thought crediting was important). Also mentions that it can be found on the GDevelop asset store

Add long description to Virtual Joystick example

---

examples/space-asteroids/README.md

Don't show in changelog 
Close https://github.com/GDevelopApp/GDevelop-examples/pull/210

Refine README of space asteroids

---

examples/platformer-jump-evaluator/platformer-jump-evaluator.json

I forgot to fill the author field

[PlatformerJumpEvaluator] Update authors.

---

examples/recolorizer/recolorizer.json

[Recolorizer] Add author id.

---

examples/load-image-from-url/load-image-from-url.json

Fix URL in "Load a sprite from an URL"

---

__tests__/post-build/exampleShortHeaders.json.spec.js
examples/bounce-and-hook/bounce-and-hook.json
examples/geometry-monster/geometry-monster.json
examples/isometric-game/isometric-game.json
examples/pairs/pairs.json
examples/platformer/platformer.json
examples/run-dino-run/run-dino-run.json
examples/space-shooter/space-shooter.json

Add the official GDevelop account on game templates.

Add GDevelop account as author on game templates

---

examples/leaderboards/leaderboards.json

Also removed unnecessary wait actions

Leaderboards: Prevent clicking during countdown

---

scripts/generate-database.js

Move down the run dino run under latest games

Add Tappy Plane on the homepage

---

examples/parking-jam/parking-jam.json

Remove the unused effect on layers

[Parking Jam] Remove the unused effect on layers

---

examples/absorbus/absorbus.json

- Added new logo on Title screen
- Changed link URL
- Made an external event to process clicks on the logo

Absorbus 1.0.1 (added links to GDevelop)

---

examples/marching-squares-qix/marching-squares-qix.json

* Upgrade the marching square extension to fix a collision issue.
The PR for the extension update:
* https://github.com/GDevelopApp/GDevelop-extensions/pull/486
* Try it: https://games.gdevelop-app.com/game-75c0adef-dd33-49d5-a152-782ffe5ed4cc/index.html

[QIX] Upgrade the marching square extension to fix a collision issue.

---

examples/marching-squares-platforms-painter/marching-squares-platforms-painter.json

* Upgrade the marching square extension to have a better collision (the character is less likely to be stuck inside the platform).
The PR for the extension update:
* https://github.com/GDevelopApp/GDevelop-extensions/pull/486
* Try it: https://games.gdevelop-app.com/game-944165b7-251a-4b91-9cad-11ca471d603f/index.html

[PlatformerPainter] Upgrade the marching square extension to have better collisions.

---

examples/ball-cup-boom/ball-cup-boom.json
scripts/generate-database.js

- Update link to edit in GDevelop
- Added "ball-cup-boom" to generate-database.js

Ball cup boom (1.0.2)

---

examples/leaderboards/leaderboards.json

@ClementPasteau this can be merged when you are ready for it.
https://liluo.io/victrisgames/leaderboard

Added Player Authentication to the Leaderboard example game

---

scripts/generate-database.js

Those were not put forward in past.

Move other examples in the homepage

---

examples/conviction-of-gun-dude-desktop/README.md
examples/conviction-of-gun-dude-mobile/README.md
examples/inventory-system/README.md

Close 
https://forum.gdevelop.io/t/typos-on-game-example-section/43927

Fix typos in game descriptions

---

examples/platformer/platformer.json

This doesn't change anything outside of the extension events being simpler.
- https://github.com/GDevelopApp/GDevelop-extensions/pull/737

[Platformer] Upgrade the button to use the new touch conditions.

---

examples/tappy-plane/tappy-plane.json

- Use external layouts
- Simplify events a bit

[Tappy Plane] Use buttons

---

examples/space-shooter/space-shooter.json

- Add a behavior to handle player animations.
- Add a behavior to destroy explosion sprites.
- Add a FSM for game states.
- Replace deprecated timer conditions.

[Space shooter] Simply events

---

examples/tappy-plane/tappy-plane.json

It needs:
- https://github.com/4ian/GDevelop/pull/4874

[Tappy Plane] Add the login banner

---

examples/fire-bullet/fire-bullet.json

See: https://github.com/GDevelopApp/GDevelop-extensions/pull/778

[FireBullet] Added bullet speed variance

---

examples/papa_is_you/papa_is_you.json

https://editor.gdevelop.io?project=https://raw.githubusercontent.com/D8H/GDevelop-examples/Papa-Is-You-Game-Example/examples/papa_is_you/papa_is_you.json

Simplify and comment "Papa is you game example"

---

examples/plinko/README.md

[Plinko] Fix a typo in a list in the description.

---

examples/goose-bomberman/goose-bomberman.json

[Goose Bomberman] Upgrade the animator behavior

---

examples/curved-movement/curved-movement.json

[Curve movement] Fix the author.

---

examples/curved-movement/curved-movement.json

[Curve movement] Upgrade the extension to fix SVG path with relative lines

---

examples/joint-connector/joint-connector.json

Prevent chain from being pulled apart and allow G to be broken by forces.

[Joint Connector] [Update] Prevent chain from being pulled apart and allow G to be broken by forces

---

.github/ISSUE_TEMPLATE/new-example.md
.github/ISSUE_TEMPLATE/report-an-issue-with-an-example.md
README.md

Updated
- Add black line
- Remove trailing whitespace
- Emphasis style consistently

Clean markdown files

---

examples/load-testing/load-testing.json

https://gd.games/VictrisGames/load-testing
https://github.com/GDevelopApp/GDevelop-examples/assets/8879811/c2b9151a-a263-4c91-93fe-09c29877ea99

[Load Testing] [Update] Add ability to drag red hero and to change scenes repeatedly

---

examples/object-slicer/object-slicer.json

Fixes https://github.com/GDevelopApp/GDevelop-extensions/issues/950

[Object Slicer] [Reviewed] [Update] Fix bug in parameter name for condition to delete object

---

examples/3d-car-coin-hunt/3d-car-coin-hunt.json

https://gd.games/gdevelop/3d-car-coin-hunt

[3D Car Coin Hunt] Fix default leaderboard configuration

---

examples/klondike-solitaire/klondike-solitaire.json

[Kondlike Solitaire] Fix cards positions after a drag is cancelled

---

examples/smoothy/smoothy.json

[Smoothy] Replace deprecated actions

---

examples/fish-school/fish-school.json

[Fish school] Upgrade Boids extension

---

examples/platformer/platformer.json

[Platformer] Update deprecated actions

---

examples/spherez/spherez.json

This is a very minor update to keep the game up to date.
(FYI - Please ignore the branch name.  I did not change to using impulse because I discovered it was already using it.)

[Spherez] Updated all deprecated actions and added the button states extension

---

scripts/generate-database.js

Sort examples that are not starters nor game by presence of thumbnails

---

examples/fish-school/fish-school.json

[Fish school] Update the extension

---

examples/multiplayer-jump-game/multiplayer-jump-game.json
examples/multiplayer-platformer-arrow-fight/multiplayer-platformer-arrow-fight.json

todo: need to fix player joining and not appearing (scenestack issue)
To be merged only when the new condition is available for everyone in GDevelop

Update Arrow Fight to allow mid-game join

---

examples/multiplayer-platformer-arrow-fight/multiplayer-platformer-arrow-fight.json

Please don't change the original projectuuid of published games

---

examples/multiplayer-platformer-arrow-fight/multiplayer-platformer-arrow-fight.json

Fix to include bots in arrow fight multiplayer game

---

examples/tappy-plane/tappy-plane.json

Mainly to ease quick customization flow by allowing to edit the title

Update tappy plane to use a title text

---

examples/starting-platformer/starting-platformer.json

Update a sound preloading for starting-platformer.json

---

examples/multiplayer-platformer-arrow-fight/multiplayer-platformer-arrow-fight.json

Update multiplayer-platformer-arrow-fight.json with the required version
